### ISSUE TITLE
Update app.js to use correct default params

### ISSUE THREAD

**Issue by dhmax88** [ournameismud/mud-fractal#4]
activeClass -> currentClass 
activeParentClass -> currentParentClass

`document.getElementById('barba-wrapper') &&
	new Router({
		routes,
		onChange: [],
		onReady: [],
		onComplete: [],
		navigation: ['header ul', 'footer ul', 'nav'],
		currentClass: 'is-current',
		currentParentClass: 'is-current-child'
}).start()`

**Comment by magicspon** [comment]
wanna make a PR?

**Comment by magicspon** [comment]
updated
